#version 430

layout(local_size_x = 128) in;
layout(std430, binding = 0) buffer Positions { vec4 positions[]; };
layout(std430, binding = 1) buffer Corrections { ivec4 corrections[]; };

#ifdef LIBMMD_VULKAN
layout(push_constant) uniform Parameters { uint ParticleCount; };
#else
uniform uint ParticleCount;
#endif

void main() {
	uint index = gl_GlobalInvocationID.x;
	if (index >= ParticleCount) return;
	ivec4 correction = corrections[index];
	if (correction.w > 0) {
		positions[index].xyz += vec3(correction.xyz) / (1000000.0 * float(correction.w));
	}
}
